### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by LiuGangR** [starcolon/photo-auto-balance#12]
I try this as the README.But it doesn't work.Just print these:

> localhost:photo-auto-balance r$ python3 loader.py --train --limit 30 --dir ./data/
/usr/local/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
/usr/local/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
=====================
Loader started ...
=====================
Executing function...
No samples in the given directory.
Ending the job now...

**Comment by starcolon** [comment]
Hi @LiuGangR thanks for your interest in the project.
Basically, the `load.py` script will look for the proper data directory as following structure:
```
data
├── out/
├── raw/
└── unfiltered/
```

All image samples should be put inside `data/raw`. Then you can execute the script as follows.

```
$ python3 loader.py --train --limit 30 --dir ./data/raw/
```

**Comment by LiuGangR** [comment]
yes，it works! And the photo should be '*.jpg' , not '*.JPG'.

**Comment by starcolon** [comment]
Awesome!

**Comment by mecury1** [comment]
> yes，it works! And the photo should be '_.jpg' , not '_.JPG'.

你好！请问你这个代码的问题解决了吗？
