### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by marbleappdev** [starcolon/photo-auto-balance#19]
@starcolon  Hi,  I would like to test some images with your model. If you could provide your trained model, that would be greatly appreciate!

**Comment by tao-pr** [comment]
Hi @marbleappdev 
Unfortunately i'm working on the completely new model structure and have a plan to ditch this lasagne-based code which causes too many inconsistency training glitches. so i no longer rely on the current code and no longer keep the trained models anymore.
